#Available PlaceHolders:
#  - %player_name% | get player's name
#  - %mined_after_join% | get the total blocks player have mined after join the server
#  - %mined_blocks% | get player's total mined blocks
#  - %mined_diamonds% | get player's total mined diamonds blocks
#  - %mined_emeralds% | get player's total mined emeradls blocks
#  - %mined_golds% | get player's total mined golds blocks
#  - %mined_irons% | get player's total mined irons blocks
#  - %mined_coals% | get player's total mined coals blocks
#  - %block_just_mined% | get the block that player just mined
#  - %progression_state% | display the player progress to get reward as percent

MySQL:
  enableMySQL: false
  username: "root"
  password: ""
  port: 3306
  databaseName: ""

HelpMessage:
  - "§e/blockbreakreward reload | to reload the plugin"
  - "§e/blockbreakreward leaderboard | to show top players"
  - "§e/blockbreakreward YamltoMySQLDatabase | transfer yaml files to database"
  - "§e/blockbreakreward help | show helps"
ReloadMessage: "§eBlock Break Reward is reloaded, have fun"
NeedPermission: "§eYou don't have permission to do use this command"
InventoryFullWarning: "§c[BlockBreakReward] your inventory is full"

EnableFullInventoryWarning: true

BlockToInventory: false

ProgressActionBar: true
ActionBarTemplate: "TOTAL: %mined_blocks% | PROGRESS: %progression_state%%"
ProgressReachSound: entity_player_levelup

SavePlayerDataAfter: 0

ExceptBlocks:
  - none

SpecificTools:
  - all

Rewards:
  Reward1:
    permission: blockbreakreward.default
    blockNeedToMine: 1000
    randomCommand: true
    commands:
      - "give %player_name% 500"
  Reward2:
    permission: blockbreakreward.opplayer
    blockNeedToMine: 5000000
    randomCommand: true
    commands:
      - "op %player_name%"
      - "eco give %player_name% 500"
      - "ban %player_name% mining too much blocks %mined_blocks%"
  Reward3:
    permission: blockbreakreward.reward3
    blockNeedToMine: 10
    randomCommand: true
    commands:
      - "give %player_name% 20"
      - "kill %player_name%"
