name: blockbreakreward
main: com.blockbreakreward.Plugin
version: 0.5
api-version: 1.16
author: TrongThang
permissions:
  blockbreakreward.reload:
    description: reload the plugin
    default: false
  blockbreakreward.help:
    description: shows help of the plugin
    default: false
commands:
  blockbreakreward:
    description: a block break reward command
